
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Mar 11 12:14:30 CET 2026
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int POW = 45;
  public static final int CONST = 5;
  public static final int CASE = 44;
  public static final int REM = 43;
  public static final int NOTEQUAL = 35;
  public static final int GREATER = 36;
  public static final int LPAREN = 12;
  public static final int SEMI = 7;
  public static final int CONTINUE = 17;
  public static final int LESS = 38;
  public static final int FOR = 22;
  public static final int MINUS = 25;
  public static final int CHARACTER = 49;
  public static final int RPAREN = 13;
  public static final int AND = 28;
  public static final int LESSEQUAL = 39;
  public static final int OR = 27;
  public static final int BOOL = 48;
  public static final int COMMA = 8;
  public static final int INC = 23;
  public static final int DIV = 42;
  public static final int PLUS = 40;
  public static final int ASSIGN = 6;
  public static final int IF = 15;
  public static final int DOT = 32;
  public static final int EOF = 0;
  public static final int RETURN = 18;
  public static final int EQUAL = 34;
  public static final int NEW = 26;
  public static final int error = 1;
  public static final int MUL = 41;
  public static final int NUMBER = 47;
  public static final int IDENT = 46;
  public static final int BREAK = 16;
  public static final int VOID = 14;
  public static final int SWITCH = 21;
  public static final int GREATEREQUAL = 37;
  public static final int COLON = 31;
  public static final int LBRACE = 3;
  public static final int ELSE = 29;
  public static final int LSQUARE = 9;
  public static final int ENUM = 11;
  public static final int READ = 19;
  public static final int RSQUARE = 10;
  public static final int RBRACE = 4;
  public static final int PROG = 2;
  public static final int QUESTION = 30;
  public static final int DEC = 24;
  public static final int PRINT = 20;
  public static final int LENGTH = 33;
}

